### ISSUE TITLE
How to stream from ip camera TP-LINK C100 , 15fps ?

### ISSUE THREAD

**Issue by leodesigndev** [xpcrts/Steaming-IP-Camera-Nodejs#11]
How to stream from camera recording at 15fps ?

**Comment by ochsec** [comment]
FFmpeg doesn't seem to work with 15 fps, but you can change the frame rate of the stream in app.js with a ffmpegoptions:


    ...
    //A channel of camera stream
    Stream = require('node-rtsp-stream');
    stream = new Stream({
        streamUrl: 'rtsp://' + username + ':' + password + '@' + ip_address +':554/live/ch0',
        wsPort: 9999,
        ffmpegOptions: {
            '-r': 30
        }
    });


After adding the option, it worked for me.
