### ISSUE TITLE
Did we customize with the multiple IP Camera through nodeJS

### ISSUE THREAD

**Issue by sajeevgeorge** [xpcrts/Steaming-IP-Camera-Nodejs#3]
Can we able to do the multiple ip camera through node js. I have tried to add multiple in app.js but not working. could you please help to achieve this and i have tried with the sample application and its takes streaming high memory.

**Comment by dalayza** [comment]
I try this but not served

**Comment by ochsec** [comment]
You can add multiple cameras if you give each one a different web socket port.

Example:

cameras.json

    {
        "cameras": [
            {
                "ip_address": "192.168.0.100",
                "username": "admin",
                "password": "admin",
                "websocket": 9991
            },
            {
                "ip_address": "192.168.0.101",
                "username": "admin",
                "password": "admin",
                "websocket": 9992
            }
        ] 
    }

app.js

    const configs = require('../cameras.config.json');

    configs.cameras.forEach(c => {
        new Stream({
            streamUrl: 'rtsp://' + c.username + ':' + c.password + '@' + c.ip_address + ':554/live/ch1',
            wsPort: c.websocket,
            ffmpegOptions: {
                '-r': 30
            }
        })
    });
