### ISSUE TITLE
step  by step

### ISSUE THREAD

**Issue by chongyangwang** [xpcrts/Steaming-IP-Camera-Nodejs#5]
能不能附一个demo的源码
want a demo code

**Comment by xpcrts** [comment]
Can check readme file on description of project.

**Comment by richaardvark** [comment]
The readme is not correct/followable.  For example:

> 1. In the repository, open app.js file

Ok... but there is no "app.js" file in the repository...?

![Screenshot 2022-05-10 231402](https://user-images.githubusercontent.com/41244847/167767972-e902be89-103a-479b-82fd-926ae0440516.png)


**Edit:** Figured it out.  If I manually download the release .zip then yes, there is an app.js file.  If I follow your directions from the read-me and run `git clone https://github.com/xpcrts/Steaming-IP-Camera-Nodejs` it does not download the same files and there is no app.js file.  I think your read-me needs to be updated.  I simply followed it exactly as you presented it and it was not correct. :-/
